In [1]:
import pandas as pd
dataframe = pd.read_csv('RAW_DATA\\survey_results_public.csv')
schema_dataframe = pd.read_csv('RAW_DATA\\survey_results_schema.csv', index_col='Column')

In [2]:
# Compute the median salary from the 'ConvertedComp' column
dataframe['ConvertedComp'].median()

57287.0

In [3]:
# Show descriptive statistics for numeric columns in the DataFrame
dataframe.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [4]:
# Compute mean of 'ConvertedComp'
dataframe['ConvertedComp'].mean()

127110.73842323056

In [5]:
# Show counts of each value in 'Hobbyist'
dataframe['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [6]:
# Show relative frequencies of 'SocialMedia' values as this is %
dataframe['SocialMedia'].value_counts(normalize=True)

SocialMedia
Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: proportion, dtype: float64

In [7]:
# Show count of respondents per country
dataframe['Country'].value_counts()

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [8]:
# Show all rows for the group 'India' from the grouped object
country_grp = dataframe.groupby(['Country'])
country_grp.get_group('India')

C:\Users\dilyadav1\AppData\Local\Temp\ipykernel_12616\3311030065.py:3: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('India')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
14,15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
49,50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
64,65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88808,77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88825,79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88853,84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88864,86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...",...,Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [9]:
# For India, show counts of 'SocialMedia' values
filt = dataframe['Country'] == 'India'
dataframe.loc[filt]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [10]:
# Show social media counts specifically for India
country_grp['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [11]:
# Median 'ConvertedComp' specifically for India
country_grp['ConvertedComp'].median().loc['India']

10080.0

In [12]:
# Count Python users in India by checking 'LanguageWorkedWith' contains 'Python'
filt = dataframe['Country'] == 'India'
dataframe.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [13]:
# Properly count Python mentions per country using apply on grouped series
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [14]:
# Create a series with counts of Python users per country
Country_respondents = dataframe['Country'].value_counts()
Country_respondents

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [15]:
# Count how many respondents per country list Python in 'LanguageWorkedWith'
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [16]:
# Combine the two series into a DataFrame
python_df = pd.concat([Country_respondents, country_uses_python], axis='columns', sort=False)
python_df

                   count  LanguageWorkedWith
Country
United States      20949               10083
India               9061                3105
Germany             5866                2451
United Kingdom      5737                2384
Canada              3395                1558
...                  ...                 ...
Tonga                  1                   0
Timor-Leste            1                   1
North Korea            1                   0
Brunei Darussalam      1                   0
Chad                   1                   0

[179 rows x 2 columns]

In [17]:
# renaming columns for clarity
python_df.rename(columns={'count':'NumRespondents', 'LanguageWorkedWith':'NumUsingPython'}, inplace=True)
python_df

                   NumRespondents  NumUsingPython
Country
United States               20949           10083
India                        9061            3105
Germany                      5866            2451
United Kingdom               5737            2384
Canada                       3395            1558
...                           ...             ...
Tonga                           1               0
Timor-Leste                     1               1
North Korea                     1               0
Brunei Darussalam               1               0
Chad                            1               0

[179 rows x 2 columns]

In [18]:
# Compute percentage of respondents per country who know Python
python_df['%knowsPython'] = (python_df['NumUsingPython'] / python_df['NumRespondents']) * 100
python_df

                   NumRespondents  NumUsingPython  %knowsPython
Country
United States               20949           10083     48.131176
India                        9061            3105     34.267741
Germany                      5866            2451     41.783157
United Kingdom               5737            2384     41.554820
Canada                       3395            1558     45.891016
...                           ...             ...           ...
Tonga                           1               0      0.000000
Timor-Leste                     1               1    100.000000
North Korea                     1               0      0.000000
Brunei Darussalam               1               0      0.000000
Chad                            1               0      0.000000

[179 rows x 3 columns]

In [19]:
# sort which country has highest percentage of Python users
python_df.sort_values(by='%knowsPython', ascending=False, inplace=True)
python_df.head(50)

                                  NumRespondents  NumUsingPython  %knowsPython
Country
Sao Tome and Principe                          1               1    100.000000
Timor-Leste                                    1               1    100.000000
Dominica                                       1               1    100.000000
Niger                                          1               1    100.000000
Turkmenistan                                   7               6     85.714286
Mauritania                                     7               5     71.428571
Guinea                                         3               2     66.666667
Bahamas                                        3               2     66.666667
Guyana                                         3               2     66.666667
Uganda                                        72              47     65.277778
Iceland                                       49              30     61.224490
Haiti                                          5               3     60.000000
Benin                                          5               3     60.000000
Namibia                                        5               3     60.000000
Congo, Republic of the...                      7               4     57.142857
Oman                                          11               6     54.545455
Cuba                                          30              16     53.333333
Republic of Korea                             39              20     51.282051
San Marino                                     2               1     50.000000
Sierra Leone                                   2               1     50.000000
Monaco                                         4               2     50.000000
South Korea                                  160              80     50.000000
Bhutan                                         2               1     50.000000
Seychelles                                     2               1     50.000000
Chile                                        206             102     49.514563
Finland                                      546             266     48.717949
Kenya                                        249             120     48.192771
United States                              20949           10083     48.131176
Israel                                       952             457     48.004202
Ecuador                                       82              39     47.560976
Taiwan                                       187              88     47.058824
Montenegro                                    17               8     47.058824
Mongolia                                      17               8     47.058824
Switzerland                                  978             460     47.034765
United Republic of Tanzania                   32              15     46.875000
Hong Kong (S.A.R.)                           188              88     46.808511
Japan                                        391             182     46.547315
Maldives                                      13               6     46.153846
Canada                                      3395            1558     45.891016
Singapore                                    303             139     45.874587
New Zealand                                  524             236     45.038168
China                                        664             297     44.728916
Honduras                                      27              12     44.444444
France                                      2391            1054     44.081974
Iraq                                          39              17     43.589744
Thailand                                     214              92     42.990654
Democratic Republic of the Congo               7               3     42.857143
Nepal                                        237             101     42.616034
Estonia                                      195              82     42.051282
Russian Federation                          1694             708     41.794569

In [20]:
# Show Python-related stats for India specifically
python_df.loc['India']

NumRespondents    9061.000000
NumUsingPython    3105.000000
%knowsPython        34.267741
Name: India, dtype: float64