In [ ]:
# Concept: Import NumPy for numeric operations and represent missing values with `np.nan`
# Remember: Use `np.nan` consistently when preparing data for pandas
import numpy as np

In [125]:
import pandas as pd

In [ ]:
# Concept: Create a small dataset demonstrating different missing-value markers
# Remember: Strings like 'NA' or 'Missing' are not np.nan until replaced
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': [
        'CoreyMSchafer@gmail.com',
        'JaneDoe@email.com',
        'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com','NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [ ]:
# Concept: Build a DataFrame from the example dictionary to inspect missing data
# Remember: Displaying the DataFrame helps decide cleaning strategy
df=pd.DataFrame(people)
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: `dropna()` removes rows with missing values by default
# Remember: Default drops any row with at least one NA (how='any')
df.dropna()

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: Explicit `axis='index'` with `how='any'` drops rows having any NA
# Remember: This is equivalent to the default `dropna()` behavior
df.dropna(axis='index', how='any')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: `how='all'` drops rows only when all values are missing
# Remember: Use when rows with at least one valid value should be kept
df.dropna(axis='index', how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: Drop columns with all missing values using `axis='columns'`
# Remember: Column-wise drops change DataFrame shape significantly
df.dropna(axis='columns', how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: Drop columns containing any missing value with `how='any'`
# Remember: This is aggressive — often not what you want for real data
df.dropna(axis='columns', how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [ ]:
# Concept: Use `subset` to limit `dropna()` to specific columns
# Remember: Only rows missing in the subset columns are considered for dropping
df.dropna(axis='index', how='any', subset=['email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: `how='all'` with subset keeps rows that have any value in the subset
# Remember: Use this when you only want to drop rows that lack all subset values
df.dropna(axis='index', how='all', subset=['email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: Combine multiple columns in `subset` to control dropping behavior
# Remember: `how='all'` vs `how='any'` yields different retention rules
df.dropna(axis='index', how='all', subset=['last','email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: Use `how='any'` with multiple subset columns to drop rows missing any of them
# Remember: This removes rows even if only one of the subset columns is missing
df.dropna(axis='index', how='any', subset=['last','email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [ ]:
# Concept: Replace sentinel strings with `np.nan` to standardize missing values
# Remember: `inplace=True` mutates the DataFrame; keep originals if needed
df2 = pd.DataFrame(people)
df2.replace('NA', np.nan, inplace=True)
df2.replace('Missing', np.nan, inplace=True)

In [ ]:
# Concept: Inspect the DataFrame after replacing sentinel values
# Remember: Confirm replacements converted string markers to actual NaN
df2

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
4    NaN      NaN                      NaN  None
5   None      NaN      Anonymous@email.com  None
6    NaN      NaN                      NaN   NaN

In [ ]:
# Concept: Drop rows missing 'email' after sentinel replacements
# Remember: Work on a copy if you need the original data preserved
df2.dropna(axis='index', how='any', subset=['email'])

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
5   None      NaN      Anonymous@email.com  None

In [ ]:
# Concept: Drop rows only when the subset columns are all missing
# Remember: This keeps rows that have at least one value in the subset
df2.dropna(axis='index', how='all', subset=['email'])

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
5   None      NaN      Anonymous@email.com  None

In [ ]:
# Concept: Use subset with multiple columns to control dropping behavior
# Remember: Choose 'all' when you only want to drop rows missing every listed column
df2.dropna(axis='index', how='all', subset=['last','email'])

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
5   None      NaN      Anonymous@email.com  None

In [ ]:
# Concept: Use 'any' to drop rows missing any of the subset columns
# Remember: This is stricter — rows missing one of the subset columns will be removed
df2.dropna(axis='index', how='any', subset=['last','email'])

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [ ]:
# Concept: `isna()` returns a boolean mask indicating missing entries
# Remember: Use the mask for conditional operations or to count missing values
df2.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [ ]:
# Concept: `fillna()` provides a simple way to replace NaNs with a value
# Remember: Prefer domain-appropriate fills; avoid misleading default values
df2.fillna('HELLOFILL')

       first       last                    email        age
0      Corey    Schafer  CoreyMSchafer@gmail.com         33
1       Jane        Doe        JaneDoe@email.com         55
2       John        Doe        JohnDoe@email.com         63
3      Chris    Schafer                HELLOFILL         36
4  HELLOFILL  HELLOFILL                HELLOFILL  HELLOFILL
5  HELLOFILL  HELLOFILL      Anonymous@email.com  HELLOFILL
6  HELLOFILL  HELLOFILL                HELLOFILL  HELLOFILL

In [ ]:
# Concept: Check column data types to plan conversions or analyses
# Remember: Non-numeric strings prevent numeric aggregation like mean
df2.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [ ]:
# Concept: Computing mean fails on non-numeric types — requires conversion
# Remember: Convert or coerce types before aggregation to avoid errors
df2['age'].mean()

TypeError: can only concatenate str (not "int") to str

In [ ]:
# Concept: Use `astype()` to cast a Series to an integer type
# Remember: Casting strings with non-numeric values will raise errors
df2['age'].astype('int')

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [ ]:
# Concept: Convert 'age' to float first to accommodate NaNs or decimal values
# Remember: Use `errors='coerce'` if you expect invalid strings you want as NaN
df2['age'] = df2['age'].astype('float')

In [ ]:
# Concept: Re-check dtypes after casting to confirm conversions succeeded
# Remember: Downstream ops (like mean) depend on correct numeric types
df2.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [ ]:
# Concept: Now that 'age' is numeric, compute its mean
# Remember: Results can be influenced by NaNs — consider `.mean(skipna=True)` or filling missing values first
df2['age'].mean()

46.75

In [ ]:
# Concept: Use `na_values` in `read_csv()` to treat sentinel strings as NaN on load
# Remember: Loading with a schema file helps document columns and types
na_vals = ['NA', 'Missing']
df3 = pd.read_csv('stack-overflow-developer-survey-2019\\survey_results_public.csv', na_values=na_vals)
schema_df3 = pd.read_csv('stack-overflow-developer-survey-2019\\survey_results_schema.csv', index_col='Column')

In [ ]:
# Concept: Inspect the loaded DataFrame to confirm expected columns and NA handling
# Remember: Large CSVs may display truncated output; use `.head()` or `.info()` when needed
df3

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [ ]:
# Concept: Peek at the first few values of `YearsCode` to inspect formatting
# Remember: Mixed types (numbers and strings) will prevent numeric aggregation
df3['YearsCode'].head(10)

0      4
1    NaN
2      3
3      3
4     16
5     13
6      6
7      8
8     12
9     12
Name: YearsCode, dtype: object

In [ ]:
# Concept: Mean requires numeric dtype — convert or coerce first
# Remember: Calling `.mean()` on non-numeric Series raises an error
df3['YearsCode'].mean()

TypeError: can only concatenate str (not "int") to str

In [ ]:
# Concept: Cast `YearsCode` to float once textual markers are handled
# Remember: Use `.replace()` to normalize special text values before casting
df3['YearsCode']= df3['YearsCode'].astype(float)

ValueError: could not convert string to float: 'Less than 1 year'

In [ ]:
# Concept: View unique values to verify replacements converted text to numeric
# Remember: Use `np.unique()` or `.unique()` to inspect distinct entries
df3['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 'Less than 1 year', '30', '9', '26', '40', '19',
       '15', '20', '28', '25', '1', '22', '11', '33', '50', '41', '18',
       '34', '24', '23', '42', '27', '21', '36', '32', '39', '38', '31',
       '37', 'More than 50 years', '29', '44', '45', '48', '46', '43',
       '47', '49'], dtype=object)

In [ ]:
# Concept: Replace textual ranges like 'Less than 1 year' with numeric proxies
# Remember: Choose proxy values that reflect domain meaning (e.g., 0.5 for <1)
df3['YearsCode'].replace('Less than 1 year', 0.5, inplace=True)
df3['YearsCode'].replace('More than 50 years', 50.5, inplace=True)

In [ ]:
# Concept: Re-check unique values after replacing textual markers
# Remember: Confirm no unexpected text remains before casting
df3['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 0.5, '30', '9', '26', '40', '19', '15', '20',
       '28', '25', '1', '22', '11', '33', '50', '41', '18', '34', '24',
       '23', '42', '27', '21', '36', '32', '39', '38', '31', '37', 50.5,
       '29', '44', '45', '48', '46', '43', '47', '49'], dtype=object)

In [ ]:
# Concept: Cast cleaned `YearsCode` to numeric for analysis
# Remember: If casting fails, inspect remaining non-numeric entries
df3['YearsCode']= df3['YearsCode'].astype(float)

In [ ]:
# Concept: Compute mean of `YearsCode` after cleaning and casting
# Remember: Mean is sensitive to outliers; consider median for robustness
df3['YearsCode'].mean()

11.66917032454684

In [ ]:
# Concept: Median provides a robust central tendency less sensitive to outliers
# Remember: Compare mean vs median to understand skew in YearsCode distribution
df3['YearsCode'].median()

9.0

In [ ]:
# Concept: `describe()` summarizes distribution (count, mean, std, quartiles)
# Remember: Use `describe()` to spot missing values and distribution shape quickly
df3['YearsCode'].describe()

count    87938.00000
mean        11.66917
std          9.14001
min          0.50000
25%          5.00000
50%          9.00000
75%         15.00000
max         50.50000
Name: YearsCode, dtype: float64